// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: C:\Users\chinmay.nerurkar\Desktop\ws\Scraper\DataLayer\capnp\schema\ydata.capnp

package datalayer.objects.msg;

public final class YDataMsg {
  public static class YData {
    public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)26,(short)5);
    public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
      public Factory() {
      }
      public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
        return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
      }
      public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
        return new Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final org.capnproto.StructSize structSize() {
        return YData.STRUCT_SIZE;
      }
      public final Reader asReader(Builder builder) {
        return builder.asReader();
      }
    }
    public static final Factory factory = new Factory();
    public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
      new org.capnproto.StructList.Factory<Builder, Reader>(factory);
    public static final class Builder extends org.capnproto.StructBuilder {
      Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
        super(segment, data, pointers, dataSize, pointerCount);
      }
      public final Reader asReader() {
        return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
      }
      public final boolean hasSymbol() {
        return !_pointerFieldIsNull(0);
      }
      public final org.capnproto.Text.Builder getSymbol() {
        return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
      }
      public final void setSymbol(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 0, value);
      }
      public final void setSymbol(String value) {
        _setPointerField(org.capnproto.Text.factory, 0, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initSymbol(int size) {
        return _initPointerField(org.capnproto.Text.factory, 0, size);
      }
      public final boolean hasName() {
        return !_pointerFieldIsNull(1);
      }
      public final org.capnproto.Text.Builder getName() {
        return _getPointerField(org.capnproto.Text.factory, 1, null, 0, 0);
      }
      public final void setName(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 1, value);
      }
      public final void setName(String value) {
        _setPointerField(org.capnproto.Text.factory, 1, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initName(int size) {
        return _initPointerField(org.capnproto.Text.factory, 1, size);
      }
      public final boolean hasStockExchange() {
        return !_pointerFieldIsNull(2);
      }
      public final org.capnproto.Text.Builder getStockExchange() {
        return _getPointerField(org.capnproto.Text.factory, 2, null, 0, 0);
      }
      public final void setStockExchange(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 2, value);
      }
      public final void setStockExchange(String value) {
        _setPointerField(org.capnproto.Text.factory, 2, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initStockExchange(int size) {
        return _initPointerField(org.capnproto.Text.factory, 2, size);
      }
      public final double getYearLow() {
        return _getDoubleField(0);
      }
      public final void setYearLow(double value) {
        _setDoubleField(0, value);
      }

      public final double getYearHigh() {
        return _getDoubleField(1);
      }
      public final void setYearHigh(double value) {
        _setDoubleField(1, value);
      }

      public final double getChangeFromYearLow() {
        return _getDoubleField(2);
      }
      public final void setChangeFromYearLow(double value) {
        _setDoubleField(2, value);
      }

      public final double getChangeFromYearHigh() {
        return _getDoubleField(3);
      }
      public final void setChangeFromYearHigh(double value) {
        _setDoubleField(3, value);
      }

      public final double getPercentChangeFromYearLow() {
        return _getDoubleField(4);
      }
      public final void setPercentChangeFromYearLow(double value) {
        _setDoubleField(4, value);
      }

      public final double getPercentChangeFromYearHigh() {
        return _getDoubleField(5);
      }
      public final void setPercentChangeFromYearHigh(double value) {
        _setDoubleField(5, value);
      }

      public final double getFiftydayMovingAverage() {
        return _getDoubleField(6);
      }
      public final void setFiftydayMovingAverage(double value) {
        _setDoubleField(6, value);
      }

      public final double getChangeFromFiftydayMovingAverage() {
        return _getDoubleField(7);
      }
      public final void setChangeFromFiftydayMovingAverage(double value) {
        _setDoubleField(7, value);
      }

      public final double getTwoHundreddayMovingAverage() {
        return _getDoubleField(8);
      }
      public final void setTwoHundreddayMovingAverage(double value) {
        _setDoubleField(8, value);
      }

      public final double getChangeFromTwoHundreddayMovingAverage() {
        return _getDoubleField(9);
      }
      public final void setChangeFromTwoHundreddayMovingAverage(double value) {
        _setDoubleField(9, value);
      }

      public final long getAverageDailyVolume() {
        return _getLongField(10);
      }
      public final void setAverageDailyVolume(long value) {
        _setLongField(10, value);
      }

      public final double getPERatio() {
        return _getDoubleField(11);
      }
      public final void setPERatio(double value) {
        _setDoubleField(11, value);
      }

      public final double getPEGRatio() {
        return _getDoubleField(12);
      }
      public final void setPEGRatio(double value) {
        _setDoubleField(12, value);
      }

      public final double getPriceSales() {
        return _getDoubleField(13);
      }
      public final void setPriceSales(double value) {
        _setDoubleField(13, value);
      }

      public final double getPriceBook() {
        return _getDoubleField(14);
      }
      public final void setPriceBook(double value) {
        _setDoubleField(14, value);
      }

      public final double getEBITDA() {
        return _getDoubleField(15);
      }
      public final void setEBITDA(double value) {
        _setDoubleField(15, value);
      }

      public final double getMarketCapitalization() {
        return _getDoubleField(16);
      }
      public final void setMarketCapitalization(double value) {
        _setDoubleField(16, value);
      }

      public final double getEarningsShare() {
        return _getDoubleField(17);
      }
      public final void setEarningsShare(double value) {
        _setDoubleField(17, value);
      }

      public final double getEPSEstimateCurrentYear() {
        return _getDoubleField(18);
      }
      public final void setEPSEstimateCurrentYear(double value) {
        _setDoubleField(18, value);
      }

      public final double getEPSEstimateNextYear() {
        return _getDoubleField(19);
      }
      public final void setEPSEstimateNextYear(double value) {
        _setDoubleField(19, value);
      }

      public final double getEPSEstimateNextQuarter() {
        return _getDoubleField(20);
      }
      public final void setEPSEstimateNextQuarter(double value) {
        _setDoubleField(20, value);
      }

      public final double getDividendShare() {
        return _getDoubleField(21);
      }
      public final void setDividendShare(double value) {
        _setDoubleField(21, value);
      }

      public final double getDividendYield() {
        return _getDoubleField(22);
      }
      public final void setDividendYield(double value) {
        _setDoubleField(22, value);
      }

      public final boolean hasExDividendDate() {
        return !_pointerFieldIsNull(3);
      }
      public final org.capnproto.Text.Builder getExDividendDate() {
        return _getPointerField(org.capnproto.Text.factory, 3, null, 0, 0);
      }
      public final void setExDividendDate(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 3, value);
      }
      public final void setExDividendDate(String value) {
        _setPointerField(org.capnproto.Text.factory, 3, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initExDividendDate(int size) {
        return _initPointerField(org.capnproto.Text.factory, 3, size);
      }
      public final boolean hasDividendPayDate() {
        return !_pointerFieldIsNull(4);
      }
      public final org.capnproto.Text.Builder getDividendPayDate() {
        return _getPointerField(org.capnproto.Text.factory, 4, null, 0, 0);
      }
      public final void setDividendPayDate(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 4, value);
      }
      public final void setDividendPayDate(String value) {
        _setPointerField(org.capnproto.Text.factory, 4, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initDividendPayDate(int size) {
        return _initPointerField(org.capnproto.Text.factory, 4, size);
      }
      public final double getPriceEPSEstimateCurrentYear() {
        return _getDoubleField(23);
      }
      public final void setPriceEPSEstimateCurrentYear(double value) {
        _setDoubleField(23, value);
      }

      public final double getPriceEPSEstimateNextYear() {
        return _getDoubleField(24);
      }
      public final void setPriceEPSEstimateNextYear(double value) {
        _setDoubleField(24, value);
      }

      public final double getOneyrTargetPrice() {
        return _getDoubleField(25);
      }
      public final void setOneyrTargetPrice(double value) {
        _setDoubleField(25, value);
      }

    }

    public static final class Reader extends org.capnproto.StructReader {
      Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
        super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

      public boolean hasSymbol() {
        return !_pointerFieldIsNull(0);
      }
      public org.capnproto.Text.Reader getSymbol() {
        return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
      }

      public boolean hasName() {
        return !_pointerFieldIsNull(1);
      }
      public org.capnproto.Text.Reader getName() {
        return _getPointerField(org.capnproto.Text.factory, 1, null, 0, 0);
      }

      public boolean hasStockExchange() {
        return !_pointerFieldIsNull(2);
      }
      public org.capnproto.Text.Reader getStockExchange() {
        return _getPointerField(org.capnproto.Text.factory, 2, null, 0, 0);
      }

      public final double getYearLow() {
        return _getDoubleField(0);
      }

      public final double getYearHigh() {
        return _getDoubleField(1);
      }

      public final double getChangeFromYearLow() {
        return _getDoubleField(2);
      }

      public final double getChangeFromYearHigh() {
        return _getDoubleField(3);
      }

      public final double getPercentChangeFromYearLow() {
        return _getDoubleField(4);
      }

      public final double getPercentChangeFromYearHigh() {
        return _getDoubleField(5);
      }

      public final double getFiftydayMovingAverage() {
        return _getDoubleField(6);
      }

      public final double getChangeFromFiftydayMovingAverage() {
        return _getDoubleField(7);
      }

      public final double getTwoHundreddayMovingAverage() {
        return _getDoubleField(8);
      }

      public final double getChangeFromTwoHundreddayMovingAverage() {
        return _getDoubleField(9);
      }

      public final long getAverageDailyVolume() {
        return _getLongField(10);
      }

      public final double getPERatio() {
        return _getDoubleField(11);
      }

      public final double getPEGRatio() {
        return _getDoubleField(12);
      }

      public final double getPriceSales() {
        return _getDoubleField(13);
      }

      public final double getPriceBook() {
        return _getDoubleField(14);
      }

      public final double getEBITDA() {
        return _getDoubleField(15);
      }

      public final double getMarketCapitalization() {
        return _getDoubleField(16);
      }

      public final double getEarningsShare() {
        return _getDoubleField(17);
      }

      public final double getEPSEstimateCurrentYear() {
        return _getDoubleField(18);
      }

      public final double getEPSEstimateNextYear() {
        return _getDoubleField(19);
      }

      public final double getEPSEstimateNextQuarter() {
        return _getDoubleField(20);
      }

      public final double getDividendShare() {
        return _getDoubleField(21);
      }

      public final double getDividendYield() {
        return _getDoubleField(22);
      }

      public boolean hasExDividendDate() {
        return !_pointerFieldIsNull(3);
      }
      public org.capnproto.Text.Reader getExDividendDate() {
        return _getPointerField(org.capnproto.Text.factory, 3, null, 0, 0);
      }

      public boolean hasDividendPayDate() {
        return !_pointerFieldIsNull(4);
      }
      public org.capnproto.Text.Reader getDividendPayDate() {
        return _getPointerField(org.capnproto.Text.factory, 4, null, 0, 0);
      }

      public final double getPriceEPSEstimateCurrentYear() {
        return _getDoubleField(23);
      }

      public final double getPriceEPSEstimateNextYear() {
        return _getDoubleField(24);
      }

      public final double getOneyrTargetPrice() {
        return _getDoubleField(25);
      }

    }

  }



public static final class Schemas {
public static final org.capnproto.SegmentReader b_f718115d8e3216e3 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000" +
   "\u00e3\u0016\u0032\u008e\u005d\u0011\u0018\u00f7" +
   "\u0050\u0000\u0000\u0000\u0001\u0000\u001a\u0000" +
   "\u002d\u009b\u001a\u00f9\u004b\u0061\u0067\u009e" +
   "\u0005\u0000\u0007\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00b2\u0002\u0000\u0000" +
   "\u003d\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0039\u0000\u0000\u0000\u00cf\u0006\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0043\u003a\\\u0055\u0073\u0065\u0072\u0073" +
   "\\\u0063\u0068\u0069\u006e\u006d\u0061\u0079" +
   "\u002e\u006e\u0065\u0072\u0075\u0072\u006b\u0061" +
   "\u0072\\\u0044\u0065\u0073\u006b\u0074\u006f" +
   "\u0070\\\u0077\u0073\\\u0053\u0063\u0072" +
   "\u0061\u0070\u0065\u0072\\\u0044\u0061\u0074" +
   "\u0061\u004c\u0061\u0079\u0065\u0072\\\u0063" +
   "\u0061\u0070\u006e\u0070\\\u0073\u0063\u0068" +
   "\u0065\u006d\u0061\\\u0079\u0064\u0061\u0074" +
   "\u0061\u002e\u0063\u0061\u0070\u006e\u0070\u003a" +
   "\u0059\u0044\u0061\u0074\u0061\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u007c\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0055\u0003\u0000\u0000\u003a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0050\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\\\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0001\u0000\u0000\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0059\u0003\u0000\u0000\u002a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0054\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0060\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0002\u0000\u0000\u0000\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u005d\u0003\u0000\u0000\u0072\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\\\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0068\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0003\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0065\u0003\u0000\u0000\u0042\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0060\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u006c\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0004\u0000\u0000\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0004\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0069\u0003\u0000\u0000\u004a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0068\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0074\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0005\u0000\u0000\u0000\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0005\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0071\u0003\u0000\u0000\u0092\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0074\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0080\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0006\u0000\u0000\u0000\u0003\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0006\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u007d\u0003\u0000\u0000\u009a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0080\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u008c\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0007\u0000\u0000\u0000\u0004\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0089\u0003\u0000\u0000\u00ca\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0090\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u009c\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0008\u0000\u0000\u0000\u0005\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0008\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0099\u0003\u0000\u0000\u00d2\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00a0\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00ac\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0009\u0000\u0000\u0000\u0006\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0009\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00a9\u0003\u0000\u0000\u00b2\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00ac\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00b8\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\n\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\n\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00b5\u0003\u0000\u0000\u0002\u0001\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00bc\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00c8\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u000b\u0000\u0000\u0000\u0008\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u000b\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00c5\u0003\u0000\u0000\u00da\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00cc\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00d8\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u000c\u0000\u0000\u0000\u0009\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u000c\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00d5\u0003\u0000\u0000\u002a\u0001\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00e0\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00ec\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\r\u0000\u0000\u0000\n\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\r\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00e9\u0003\u0000\u0000\u009a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00ec\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00f8\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u000e\u0000\u0000\u0000\u000b\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u000e\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00f5\u0003\u0000\u0000\u0042\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00f0\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00fc\u0003\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u000f\u0000\u0000\u0000\u000c\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u000f\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00f9\u0003\u0000\u0000\u004a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00f8\u0003\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0004\u0004\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0010\u0000\u0000\u0000\r\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0010\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0004\u0000\u0000\u005a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0004\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u000c\u0004\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0011\u0000\u0000\u0000\u000e\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0011\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0009\u0004\u0000\u0000\u0052\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0008\u0004\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0014\u0004\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0012\u0000\u0000\u0000\u000f\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0012\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0011\u0004\u0000\u0000\u003a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0004\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0018\u0004\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0013\u0000\u0000\u0000\u0010\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0013\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0004\u0000\u0000\u00aa\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0018\u0004\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0024\u0004\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0014\u0000\u0000\u0000\u0011\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0014\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0021\u0004\u0000\u0000\u0072\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0020\u0004\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u002c\u0004\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0015\u0000\u0000\u0000\u0012\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0015\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0029\u0004\u0000\u0000\u00ba\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u002c\u0004\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0038\u0004\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0016\u0000\u0000\u0000\u0013\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0016\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0035\u0004\u0000\u0000\u00a2\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0038\u0004\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0044\u0004\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0017\u0000\u0000\u0000\u0014\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0017\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0041\u0004\u0000\u0000\u00ba\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0044\u0004\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0050\u0004\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0018\u0000\u0000\u0000\u0015\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0018\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u004d\u0004\u0000\u0000\u0072\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u004c\u0004\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0058\u0004\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0019\u0000\u0000\u0000\u0016\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0019\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0055\u0004\u0000\u0000\u0072\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0054\u0004\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0060\u0004\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u001a\u0000\u0000\u0000\u0003\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u001a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u005d\u0004\u0000\u0000\u007a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\\\u0004\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0068\u0004\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u001b\u0000\u0000\u0000\u0004\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u001b\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0065\u0004\u0000\u0000\u0082\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0064\u0004\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0070\u0004\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u001c\u0000\u0000\u0000\u0017\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u001c\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u006d\u0004\u0000\u0000\u00e2\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0074\u0004\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0080\u0004\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u001d\u0000\u0000\u0000\u0018\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u001d\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u007d\u0004\u0000\u0000\u00ca\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0084\u0004\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0090\u0004\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u001e\u0000\u0000\u0000\u0019\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u001e\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u008d\u0004\u0000\u0000\u008a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0090\u0004\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u009c\u0004\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0073\u0079\u006d\u0062\u006f\u006c\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u006e\u0061\u006d\u0065\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0073\u0074\u006f\u0063\u006b\u0045\u0078\u0063" +
   "\u0068\u0061\u006e\u0067\u0065\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0079\u0065\u0061\u0072\u004c\u006f\u0077\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0079\u0065\u0061\u0072\u0048\u0069\u0067\u0068" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0063\u0068\u0061\u006e\u0067\u0065\u0046\u0072" +
   "\u006f\u006d\u0059\u0065\u0061\u0072\u004c\u006f" +
   "\u0077\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0063\u0068\u0061\u006e\u0067\u0065\u0046\u0072" +
   "\u006f\u006d\u0059\u0065\u0061\u0072\u0048\u0069" +
   "\u0067\u0068\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0070\u0065\u0072\u0063\u0065\u006e\u0074\u0043" +
   "\u0068\u0061\u006e\u0067\u0065\u0046\u0072\u006f" +
   "\u006d\u0059\u0065\u0061\u0072\u004c\u006f\u0077" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0070\u0065\u0072\u0063\u0065\u006e\u0074\u0043" +
   "\u0068\u0061\u006e\u0067\u0065\u0046\u0072\u006f" +
   "\u006d\u0059\u0065\u0061\u0072\u0048\u0069\u0067" +
   "\u0068\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0066\u0069\u0066\u0074\u0079\u0064\u0061\u0079" +
   "\u004d\u006f\u0076\u0069\u006e\u0067\u0041\u0076" +
   "\u0065\u0072\u0061\u0067\u0065\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0063\u0068\u0061\u006e\u0067\u0065\u0046\u0072" +
   "\u006f\u006d\u0046\u0069\u0066\u0074\u0079\u0064" +
   "\u0061\u0079\u004d\u006f\u0076\u0069\u006e\u0067" +
   "\u0041\u0076\u0065\u0072\u0061\u0067\u0065\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0074\u0077\u006f\u0048\u0075\u006e\u0064\u0072" +
   "\u0065\u0064\u0064\u0061\u0079\u004d\u006f\u0076" +
   "\u0069\u006e\u0067\u0041\u0076\u0065\u0072\u0061" +
   "\u0067\u0065\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0063\u0068\u0061\u006e\u0067\u0065\u0046\u0072" +
   "\u006f\u006d\u0054\u0077\u006f\u0048\u0075\u006e" +
   "\u0064\u0072\u0065\u0064\u0064\u0061\u0079\u004d" +
   "\u006f\u0076\u0069\u006e\u0067\u0041\u0076\u0065" +
   "\u0072\u0061\u0067\u0065\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0076\u0065\u0072\u0061\u0067\u0065\u0044" +
   "\u0061\u0069\u006c\u0079\u0056\u006f\u006c\u0075" +
   "\u006d\u0065\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0009\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0009\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0070\u0045\u0052\u0061\u0074\u0069\u006f\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0070\u0045\u0047\u0052\u0061\u0074\u0069\u006f" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0070\u0072\u0069\u0063\u0065\u0053\u0061\u006c" +
   "\u0065\u0073\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0070\u0072\u0069\u0063\u0065\u0042\u006f\u006f" +
   "\u006b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0065\u0042\u0049\u0054\u0044\u0041\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u006d\u0061\u0072\u006b\u0065\u0074\u0043\u0061" +
   "\u0070\u0069\u0074\u0061\u006c\u0069\u007a\u0061" +
   "\u0074\u0069\u006f\u006e\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0065\u0061\u0072\u006e\u0069\u006e\u0067\u0073" +
   "\u0053\u0068\u0061\u0072\u0065\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0065\u0050\u0053\u0045\u0073\u0074\u0069\u006d" +
   "\u0061\u0074\u0065\u0043\u0075\u0072\u0072\u0065" +
   "\u006e\u0074\u0059\u0065\u0061\u0072\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0065\u0050\u0053\u0045\u0073\u0074\u0069\u006d" +
   "\u0061\u0074\u0065\u004e\u0065\u0078\u0074\u0059" +
   "\u0065\u0061\u0072\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0065\u0050\u0053\u0045\u0073\u0074\u0069\u006d" +
   "\u0061\u0074\u0065\u004e\u0065\u0078\u0074\u0051" +
   "\u0075\u0061\u0072\u0074\u0065\u0072\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0064\u0069\u0076\u0069\u0064\u0065\u006e\u0064" +
   "\u0053\u0068\u0061\u0072\u0065\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0064\u0069\u0076\u0069\u0064\u0065\u006e\u0064" +
   "\u0059\u0069\u0065\u006c\u0064\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0065\u0078\u0044\u0069\u0076\u0069\u0064\u0065" +
   "\u006e\u0064\u0044\u0061\u0074\u0065\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0064\u0069\u0076\u0069\u0064\u0065\u006e\u0064" +
   "\u0050\u0061\u0079\u0044\u0061\u0074\u0065\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0070\u0072\u0069\u0063\u0065\u0045\u0050\u0053" +
   "\u0045\u0073\u0074\u0069\u006d\u0061\u0074\u0065" +
   "\u0043\u0075\u0072\u0072\u0065\u006e\u0074\u0059" +
   "\u0065\u0061\u0072\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0070\u0072\u0069\u0063\u0065\u0045\u0050\u0053" +
   "\u0045\u0073\u0074\u0069\u006d\u0061\u0074\u0065" +
   "\u004e\u0065\u0078\u0074\u0059\u0065\u0061\u0072" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u006f\u006e\u0065\u0079\u0072\u0054\u0061\u0072" +
   "\u0067\u0065\u0074\u0050\u0072\u0069\u0063\u0065" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
}
}

