// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: ydata.capnp

package datalayer.objects;

public final class YDataCP {
	public static class YData {
		public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize(
				(short) 20, (short) 3);

		public static final class Factory extends
				org.capnproto.StructFactory<Builder, Reader> {
			public Factory() {
			}

			public final Reader constructReader(
					org.capnproto.SegmentReader segment, int data,
					int pointers, int dataSize, short pointerCount,
					int nestingLimit) {
				return new Reader(segment, data, pointers, dataSize,
						pointerCount, nestingLimit);
			}

			public final Builder constructBuilder(
					org.capnproto.SegmentBuilder segment, int data,
					int pointers, int dataSize, short pointerCount) {
				return new Builder(segment, data, pointers, dataSize,
						pointerCount);
			}

			public final org.capnproto.StructSize structSize() {
				return YData.STRUCT_SIZE;
			}

			public final Reader asReader(Builder builder) {
				return builder.asReader();
			}
		}

		public static final Factory factory = new Factory();
		public static final org.capnproto.StructList.Factory<Builder, Reader> listFactory = new org.capnproto.StructList.Factory<Builder, Reader>(
				factory);

		public static final class Builder extends org.capnproto.StructBuilder {
			Builder(org.capnproto.SegmentBuilder segment, int data,
					int pointers, int dataSize, short pointerCount) {
				super(segment, data, pointers, dataSize, pointerCount);
			}

			public final Reader asReader() {
				return new Reader(segment, data, pointers, dataSize,
						pointerCount, 0x7fffffff);
			}

			public final boolean hasSymbol() {
				return !_pointerFieldIsNull(0);
			}

			public final org.capnproto.Text.Builder getSymbol() {
				return _getPointerField(org.capnproto.Text.factory, 0, null, 0,
						0);
			}

			public final void setSymbol(org.capnproto.Text.Reader value) {
				_setPointerField(org.capnproto.Text.factory, 0, value);
			}

			public final void setSymbol(String value) {
				_setPointerField(org.capnproto.Text.factory, 0,
						new org.capnproto.Text.Reader(value));
			}

			public final org.capnproto.Text.Builder initSymbol(int size) {
				return _initPointerField(org.capnproto.Text.factory, 0, size);
			}

			public final boolean hasName() {
				return !_pointerFieldIsNull(1);
			}

			public final org.capnproto.Text.Builder getName() {
				return _getPointerField(org.capnproto.Text.factory, 1, null, 0,
						0);
			}

			public final void setName(org.capnproto.Text.Reader value) {
				_setPointerField(org.capnproto.Text.factory, 1, value);
			}

			public final void setName(String value) {
				_setPointerField(org.capnproto.Text.factory, 1,
						new org.capnproto.Text.Reader(value));
			}

			public final org.capnproto.Text.Builder initName(int size) {
				return _initPointerField(org.capnproto.Text.factory, 1, size);
			}

			public final double getYearLow() {
				return _getDoubleField(0);
			}

			public final void setYearLow(double value) {
				_setDoubleField(0, value);
			}

			public final double getYearHigh() {
				return _getDoubleField(1);
			}

			public final void setYearHigh(double value) {
				_setDoubleField(1, value);
			}

			public final double getFiftydayMovingAverage() {
				return _getDoubleField(2);
			}

			public final void setFiftydayMovingAverage(double value) {
				_setDoubleField(2, value);
			}

			public final double getChangeFromFiftydayMovingAverage() {
				return _getDoubleField(3);
			}

			public final void setChangeFromFiftydayMovingAverage(double value) {
				_setDoubleField(3, value);
			}

			public final double getTwoHundreddayMovingAverage() {
				return _getDoubleField(4);
			}

			public final void setTwoHundreddayMovingAverage(double value) {
				_setDoubleField(4, value);
			}

			public final double getChangeFromTwoHundreddayMovingAverage() {
				return _getDoubleField(5);
			}

			public final void setChangeFromTwoHundreddayMovingAverage(
					double value) {
				_setDoubleField(5, value);
			}

			public final long getAverageDailyVolume() {
				return _getLongField(6);
			}

			public final void setAverageDailyVolume(long value) {
				_setLongField(6, value);
			}

			public final double getPERatio() {
				return _getDoubleField(7);
			}

			public final void setPERatio(double value) {
				_setDoubleField(7, value);
			}

			public final double getPEGRatio() {
				return _getDoubleField(8);
			}

			public final void setPEGRatio(double value) {
				_setDoubleField(8, value);
			}

			public final double getEBITDA() {
				return _getDoubleField(9);
			}

			public final void setEBITDA(double value) {
				_setDoubleField(9, value);
			}

			public final double getMarketCapitalization() {
				return _getDoubleField(10);
			}

			public final void setMarketCapitalization(double value) {
				_setDoubleField(10, value);
			}

			public final double getEarningsShare() {
				return _getDoubleField(11);
			}

			public final void setEarningsShare(double value) {
				_setDoubleField(11, value);
			}

			public final double getEPSEstimateCurrentYear() {
				return _getDoubleField(12);
			}

			public final void setEPSEstimateCurrentYear(double value) {
				_setDoubleField(12, value);
			}

			public final double getEPSEstimateNextYear() {
				return _getDoubleField(13);
			}

			public final void setEPSEstimateNextYear(double value) {
				_setDoubleField(13, value);
			}

			public final double getEPSEstimateNextQuarter() {
				return _getDoubleField(14);
			}

			public final void setEPSEstimateNextQuarter(double value) {
				_setDoubleField(14, value);
			}

			public final double getDividendShare() {
				return _getDoubleField(15);
			}

			public final void setDividendShare(double value) {
				_setDoubleField(15, value);
			}

			public final double getDividendYield() {
				return _getDoubleField(16);
			}

			public final void setDividendYield(double value) {
				_setDoubleField(16, value);
			}

			public final boolean hasExDividendDate() {
				return !_pointerFieldIsNull(2);
			}

			public final org.capnproto.Text.Builder getExDividendDate() {
				return _getPointerField(org.capnproto.Text.factory, 2, null, 0,
						0);
			}

			public final void setExDividendDate(org.capnproto.Text.Reader value) {
				_setPointerField(org.capnproto.Text.factory, 2, value);
			}

			public final void setExDividendDate(String value) {
				_setPointerField(org.capnproto.Text.factory, 2,
						new org.capnproto.Text.Reader(value));
			}

			public final org.capnproto.Text.Builder initExDividendDate(int size) {
				return _initPointerField(org.capnproto.Text.factory, 2, size);
			}

			public final double getPriceEPSEstimateCurrentYear() {
				return _getDoubleField(17);
			}

			public final void setPriceEPSEstimateCurrentYear(double value) {
				_setDoubleField(17, value);
			}

			public final double getPriceEPSEstimateNextYear() {
				return _getDoubleField(18);
			}

			public final void setPriceEPSEstimateNextYear(double value) {
				_setDoubleField(18, value);
			}

			public final double getOneyrTargetPrice() {
				return _getDoubleField(19);
			}

			public final void setOneyrTargetPrice(double value) {
				_setDoubleField(19, value);
			}

		}

		public static final class Reader extends org.capnproto.StructReader {
			Reader(org.capnproto.SegmentReader segment, int data, int pointers,
					int dataSize, short pointerCount, int nestingLimit) {
				super(segment, data, pointers, dataSize, pointerCount,
						nestingLimit);
			}

			public boolean hasSymbol() {
				return !_pointerFieldIsNull(0);
			}

			public org.capnproto.Text.Reader getSymbol() {
				return _getPointerField(org.capnproto.Text.factory, 0, null, 0,
						0);
			}

			public boolean hasName() {
				return !_pointerFieldIsNull(1);
			}

			public org.capnproto.Text.Reader getName() {
				return _getPointerField(org.capnproto.Text.factory, 1, null, 0,
						0);
			}

			public final double getYearLow() {
				return _getDoubleField(0);
			}

			public final double getYearHigh() {
				return _getDoubleField(1);
			}

			public final double getFiftydayMovingAverage() {
				return _getDoubleField(2);
			}

			public final double getChangeFromFiftydayMovingAverage() {
				return _getDoubleField(3);
			}

			public final double getTwoHundreddayMovingAverage() {
				return _getDoubleField(4);
			}

			public final double getChangeFromTwoHundreddayMovingAverage() {
				return _getDoubleField(5);
			}

			public final long getAverageDailyVolume() {
				return _getLongField(6);
			}

			public final double getPERatio() {
				return _getDoubleField(7);
			}

			public final double getPEGRatio() {
				return _getDoubleField(8);
			}

			public final double getEBITDA() {
				return _getDoubleField(9);
			}

			public final double getMarketCapitalization() {
				return _getDoubleField(10);
			}

			public final double getEarningsShare() {
				return _getDoubleField(11);
			}

			public final double getEPSEstimateCurrentYear() {
				return _getDoubleField(12);
			}

			public final double getEPSEstimateNextYear() {
				return _getDoubleField(13);
			}

			public final double getEPSEstimateNextQuarter() {
				return _getDoubleField(14);
			}

			public final double getDividendShare() {
				return _getDoubleField(15);
			}

			public final double getDividendYield() {
				return _getDoubleField(16);
			}

			public boolean hasExDividendDate() {
				return !_pointerFieldIsNull(2);
			}

			public org.capnproto.Text.Reader getExDividendDate() {
				return _getPointerField(org.capnproto.Text.factory, 2, null, 0,
						0);
			}

			public final double getPriceEPSEstimateCurrentYear() {
				return _getDoubleField(17);
			}

			public final double getPriceEPSEstimateNextYear() {
				return _getDoubleField(18);
			}

			public final double getOneyrTargetPrice() {
				return _getDoubleField(19);
			}

		}

	}

	public static final class Schemas {
		public static final org.capnproto.SegmentReader b_a7fab4b6842b195f = org.capnproto.GeneratedClassSupport
				.decodeRawBytes("\u0000\u0000\u0000\u0000\u0005\u0000\u0006\u0000"
						+ "\u005f\u0019\u002b\u0084\u00b6\u00b4\u00fa\u00a7"
						+ "\u000c\u0000\u0000\u0000\u0001\u0000\u0014\u0000"
						+ "\u0089\u00a1\u00fd\u0097\u0035\u0074\u007e\u009c"
						+ "\u0003\u0000\u0007\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0015\u0000\u0000\u0000\u0092\u0000\u0000\u0000"
						+ "\u001d\u0000\u0000\u0000\u0007\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0019\u0000\u0000\u0000\u000f\u0005\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0079\u0064\u0061\u0074\u0061\u002e\u0063\u0061"
						+ "\u0070\u006e\u0070\u003a\u0059\u0044\u0061\u0074"
						+ "\u0061\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000"
						+ "\\\u0000\u0000\u0000\u0003\u0000\u0004\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0075\u0002\u0000\u0000\u003a\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0070\u0002\u0000\u0000\u0003\u0000\u0001\u0000"
						+ "\u007c\u0002\u0000\u0000\u0002\u0000\u0001\u0000"
						+ "\u0001\u0000\u0000\u0000\u0001\u0000\u0000\u0000"
						+ "\u0000\u0000\u0001\u0000\u0001\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0079\u0002\u0000\u0000\u002a\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0074\u0002\u0000\u0000\u0003\u0000\u0001\u0000"
						+ "\u0080\u0002\u0000\u0000\u0002\u0000\u0001\u0000"
						+ "\u0002\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0001\u0000\u0002\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u007d\u0002\u0000\u0000\u0042\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0078\u0002\u0000\u0000\u0003\u0000\u0001\u0000"
						+ "\u0084\u0002\u0000\u0000\u0002\u0000\u0001\u0000"
						+ "\u0003\u0000\u0000\u0000\u0001\u0000\u0000\u0000"
						+ "\u0000\u0000\u0001\u0000\u0003\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0081\u0002\u0000\u0000\u004a\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0080\u0002\u0000\u0000\u0003\u0000\u0001\u0000"
						+ "\u008c\u0002\u0000\u0000\u0002\u0000\u0001\u0000"
						+ "\u0004\u0000\u0000\u0000\u0002\u0000\u0000\u0000"
						+ "\u0000\u0000\u0001\u0000\u0004\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0089\u0002\u0000\u0000\u00b2\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u008c\u0002\u0000\u0000\u0003\u0000\u0001\u0000"
						+ "\u0098\u0002\u0000\u0000\u0002\u0000\u0001\u0000"
						+ "\u0005\u0000\u0000\u0000\u0003\u0000\u0000\u0000"
						+ "\u0000\u0000\u0001\u0000\u0005\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0095\u0002\u0000\u0000\u0002\u0001\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u009c\u0002\u0000\u0000\u0003\u0000\u0001\u0000"
						+ "\u00a8\u0002\u0000\u0000\u0002\u0000\u0001\u0000"
						+ "\u0006\u0000\u0000\u0000\u0004\u0000\u0000\u0000"
						+ "\u0000\u0000\u0001\u0000\u0006\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u00a5\u0002\u0000\u0000\u00da\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u00ac\u0002\u0000\u0000\u0003\u0000\u0001\u0000"
						+ "\u00b8\u0002\u0000\u0000\u0002\u0000\u0001\u0000"
						+ "\u0007\u0000\u0000\u0000\u0005\u0000\u0000\u0000"
						+ "\u0000\u0000\u0001\u0000\u0007\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u00b5\u0002\u0000\u0000\u002a\u0001\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u00c0\u0002\u0000\u0000\u0003\u0000\u0001\u0000"
						+ "\u00cc\u0002\u0000\u0000\u0002\u0000\u0001\u0000"
						+ "\u0008\u0000\u0000\u0000\u0006\u0000\u0000\u0000"
						+ "\u0000\u0000\u0001\u0000\u0008\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u00c9\u0002\u0000\u0000\u009a\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u00cc\u0002\u0000\u0000\u0003\u0000\u0001\u0000"
						+ "\u00d8\u0002\u0000\u0000\u0002\u0000\u0001\u0000"
						+ "\u0009\u0000\u0000\u0000\u0007\u0000\u0000\u0000"
						+ "\u0000\u0000\u0001\u0000\u0009\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u00d5\u0002\u0000\u0000\u0042\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u00d0\u0002\u0000\u0000\u0003\u0000\u0001\u0000"
						+ "\u00dc\u0002\u0000\u0000\u0002\u0000\u0001\u0000"
						+ "\n\u0000\u0000\u0000\u0008\u0000\u0000\u0000"
						+ "\u0000\u0000\u0001\u0000\n\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u00d9\u0002\u0000\u0000\u004a\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u00d8\u0002\u0000\u0000\u0003\u0000\u0001\u0000"
						+ "\u00e4\u0002\u0000\u0000\u0002\u0000\u0001\u0000"
						+ "\u000b\u0000\u0000\u0000\u0009\u0000\u0000\u0000"
						+ "\u0000\u0000\u0001\u0000\u000b\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u00e1\u0002\u0000\u0000\u003a\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u00dc\u0002\u0000\u0000\u0003\u0000\u0001\u0000"
						+ "\u00e8\u0002\u0000\u0000\u0002\u0000\u0001\u0000"
						+ "\u000c\u0000\u0000\u0000\n\u0000\u0000\u0000"
						+ "\u0000\u0000\u0001\u0000\u000c\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u00e5\u0002\u0000\u0000\u00aa\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u00e8\u0002\u0000\u0000\u0003\u0000\u0001\u0000"
						+ "\u00f4\u0002\u0000\u0000\u0002\u0000\u0001\u0000"
						+ "\r\u0000\u0000\u0000\u000b\u0000\u0000\u0000"
						+ "\u0000\u0000\u0001\u0000\r\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u00f1\u0002\u0000\u0000\u0072\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u00f0\u0002\u0000\u0000\u0003\u0000\u0001\u0000"
						+ "\u00fc\u0002\u0000\u0000\u0002\u0000\u0001\u0000"
						+ "\u000e\u0000\u0000\u0000\u000c\u0000\u0000\u0000"
						+ "\u0000\u0000\u0001\u0000\u000e\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u00f9\u0002\u0000\u0000\u00ba\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u00fc\u0002\u0000\u0000\u0003\u0000\u0001\u0000"
						+ "\u0008\u0003\u0000\u0000\u0002\u0000\u0001\u0000"
						+ "\u000f\u0000\u0000\u0000\r\u0000\u0000\u0000"
						+ "\u0000\u0000\u0001\u0000\u000f\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0005\u0003\u0000\u0000\u00a2\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0008\u0003\u0000\u0000\u0003\u0000\u0001\u0000"
						+ "\u0014\u0003\u0000\u0000\u0002\u0000\u0001\u0000"
						+ "\u0010\u0000\u0000\u0000\u000e\u0000\u0000\u0000"
						+ "\u0000\u0000\u0001\u0000\u0010\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0011\u0003\u0000\u0000\u00ba\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0014\u0003\u0000\u0000\u0003\u0000\u0001\u0000"
						+ "\u0020\u0003\u0000\u0000\u0002\u0000\u0001\u0000"
						+ "\u0011\u0000\u0000\u0000\u000f\u0000\u0000\u0000"
						+ "\u0000\u0000\u0001\u0000\u0011\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u001d\u0003\u0000\u0000\u0072\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u001c\u0003\u0000\u0000\u0003\u0000\u0001\u0000"
						+ "\u0028\u0003\u0000\u0000\u0002\u0000\u0001\u0000"
						+ "\u0012\u0000\u0000\u0000\u0010\u0000\u0000\u0000"
						+ "\u0000\u0000\u0001\u0000\u0012\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0025\u0003\u0000\u0000\u0072\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0024\u0003\u0000\u0000\u0003\u0000\u0001\u0000"
						+ "\u0030\u0003\u0000\u0000\u0002\u0000\u0001\u0000"
						+ "\u0013\u0000\u0000\u0000\u0002\u0000\u0000\u0000"
						+ "\u0000\u0000\u0001\u0000\u0013\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u002d\u0003\u0000\u0000\u007a\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u002c\u0003\u0000\u0000\u0003\u0000\u0001\u0000"
						+ "\u0038\u0003\u0000\u0000\u0002\u0000\u0001\u0000"
						+ "\u0014\u0000\u0000\u0000\u0011\u0000\u0000\u0000"
						+ "\u0000\u0000\u0001\u0000\u0014\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0035\u0003\u0000\u0000\u00e2\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u003c\u0003\u0000\u0000\u0003\u0000\u0001\u0000"
						+ "\u0048\u0003\u0000\u0000\u0002\u0000\u0001\u0000"
						+ "\u0015\u0000\u0000\u0000\u0012\u0000\u0000\u0000"
						+ "\u0000\u0000\u0001\u0000\u0015\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0045\u0003\u0000\u0000\u00ca\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u004c\u0003\u0000\u0000\u0003\u0000\u0001\u0000"
						+ "\u0058\u0003\u0000\u0000\u0002\u0000\u0001\u0000"
						+ "\u0016\u0000\u0000\u0000\u0013\u0000\u0000\u0000"
						+ "\u0000\u0000\u0001\u0000\u0016\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0055\u0003\u0000\u0000\u008a\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0058\u0003\u0000\u0000\u0003\u0000\u0001\u0000"
						+ "\u0064\u0003\u0000\u0000\u0002\u0000\u0001\u0000"
						+ "\u0073\u0079\u006d\u0062\u006f\u006c\u0000\u0000"
						+ "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u006e\u0061\u006d\u0065\u0000\u0000\u0000\u0000"
						+ "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0079\u0065\u0061\u0072\u004c\u006f\u0077\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0079\u0065\u0061\u0072\u0048\u0069\u0067\u0068"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0066\u0069\u0066\u0074\u0079\u0064\u0061\u0079"
						+ "\u004d\u006f\u0076\u0069\u006e\u0067\u0041\u0076"
						+ "\u0065\u0072\u0061\u0067\u0065\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0063\u0068\u0061\u006e\u0067\u0065\u0046\u0072"
						+ "\u006f\u006d\u0046\u0069\u0066\u0074\u0079\u0064"
						+ "\u0061\u0079\u004d\u006f\u0076\u0069\u006e\u0067"
						+ "\u0041\u0076\u0065\u0072\u0061\u0067\u0065\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0074\u0077\u006f\u0048\u0075\u006e\u0064\u0072"
						+ "\u0065\u0064\u0064\u0061\u0079\u004d\u006f\u0076"
						+ "\u0069\u006e\u0067\u0041\u0076\u0065\u0072\u0061"
						+ "\u0067\u0065\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0063\u0068\u0061\u006e\u0067\u0065\u0046\u0072"
						+ "\u006f\u006d\u0054\u0077\u006f\u0048\u0075\u006e"
						+ "\u0064\u0072\u0065\u0064\u0064\u0061\u0079\u004d"
						+ "\u006f\u0076\u0069\u006e\u0067\u0041\u0076\u0065"
						+ "\u0072\u0061\u0067\u0065\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0061\u0076\u0065\u0072\u0061\u0067\u0065\u0044"
						+ "\u0061\u0069\u006c\u0079\u0056\u006f\u006c\u0075"
						+ "\u006d\u0065\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0009\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0009\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0070\u0045\u0052\u0061\u0074\u0069\u006f\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0070\u0045\u0047\u0052\u0061\u0074\u0069\u006f"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0065\u0042\u0049\u0054\u0044\u0041\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u006d\u0061\u0072\u006b\u0065\u0074\u0043\u0061"
						+ "\u0070\u0069\u0074\u0061\u006c\u0069\u007a\u0061"
						+ "\u0074\u0069\u006f\u006e\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0065\u0061\u0072\u006e\u0069\u006e\u0067\u0073"
						+ "\u0053\u0068\u0061\u0072\u0065\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0065\u0050\u0053\u0045\u0073\u0074\u0069\u006d"
						+ "\u0061\u0074\u0065\u0043\u0075\u0072\u0072\u0065"
						+ "\u006e\u0074\u0059\u0065\u0061\u0072\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0065\u0050\u0053\u0045\u0073\u0074\u0069\u006d"
						+ "\u0061\u0074\u0065\u004e\u0065\u0078\u0074\u0059"
						+ "\u0065\u0061\u0072\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0065\u0050\u0053\u0045\u0073\u0074\u0069\u006d"
						+ "\u0061\u0074\u0065\u004e\u0065\u0078\u0074\u0051"
						+ "\u0075\u0061\u0072\u0074\u0065\u0072\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0064\u0069\u0076\u0069\u0064\u0065\u006e\u0064"
						+ "\u0053\u0068\u0061\u0072\u0065\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0064\u0069\u0076\u0069\u0064\u0065\u006e\u0064"
						+ "\u0059\u0069\u0065\u006c\u0064\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0065\u0078\u0044\u0069\u0076\u0069\u0064\u0065"
						+ "\u006e\u0064\u0044\u0061\u0074\u0065\u0000\u0000"
						+ "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0070\u0072\u0069\u0063\u0065\u0045\u0050\u0053"
						+ "\u0045\u0073\u0074\u0069\u006d\u0061\u0074\u0065"
						+ "\u0043\u0075\u0072\u0072\u0065\u006e\u0074\u0059"
						+ "\u0065\u0061\u0072\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0070\u0072\u0069\u0063\u0065\u0045\u0050\u0053"
						+ "\u0045\u0073\u0074\u0069\u006d\u0061\u0074\u0065"
						+ "\u004e\u0065\u0078\u0074\u0059\u0065\u0061\u0072"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u006f\u006e\u0065\u0079\u0072\u0054\u0061\u0072"
						+ "\u0067\u0065\u0074\u0050\u0072\u0069\u0063\u0065"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u000b\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
						+ "");
	}
}
